### ISSUE TITLE
AddBack after RemoveFront is broken

### ISSUE THREAD

**Issue by stangelandcl** [tejacques/Deque#2]
This test fails.

```
        [Test]
        public void TestAddBack()
        {
            Deque<int> deque = new Deque<int>();           
            deque.AddBack(1);
            deque.RemoveFront();
            deque.AddBack(1);
            Assert.AreEqual(1, deque.RemoveFront());                      
        }
```

Change `AddBack()` to use this 
`buffer[toBufferIndex(this.Count)] = item;`
instead of 
`buffer[toBufferIndex(this.startOffset + this.Count)] = item;`
to fix it. And thanks, this class is useful.

**Comment by tejacques** [comment]
Thanks for pointing this out! I will push out this fix ASAP.

**Comment by tejacques** [comment]
This fix is up on NuGet now. Thanks again for finding this.
